### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Kubikx** [Vexatos/ForecastersBackpacks#5]
I have logistic backpack and trying to pick up a potatoe.

---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 23.2.16 8:40
Description: Ticking player

java.lang.AbstractMethodError: redgear.morebackpacks.backpacks.BackpackLogistic.isValidItem(Lnet/minecraft/item/ItemStack;)Z
    at forestry.storage.PickupHandlerStorage.onItemPickup(PickupHandlerStorage.java:57)
    at forestry.core.EventHandlerCore.handleItemPickup(EventHandlerCore.java:47)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_17_EventHandlerCore_handleItemPickup_EntityItemPickupEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:345)
    at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:609)
    at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:600)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
    at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
    at net.minecraft.network.play.client.C03PacketPlayer$C05PacketPlayerLook.func_148833_a(SourceFile:98)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at forestry.storage.PickupHandlerStorage.onItemPickup(PickupHandlerStorage.java:57)
    at forestry.core.EventHandlerCore.handleItemPickup(EventHandlerCore.java:47)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_17_EventHandlerCore_handleItemPickup_EntityItemPickupEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:345)
    at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:609)
    at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:600)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)

-- Player being ticked --
Details:
    Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
    Entity ID: 138895
    Entity Name: xNxExOx
    Entity's Exact location: 90,30, 65,00, 225,01
    Entity's Block location: World: (90,65,225), Chunk: (at 10,4,1 in 5,14; contains blocks 80,0,224 to 95,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Entity's Momentum: 0,00, -0,08, 0,00
Stacktrace:
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
    at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
    at net.minecraft.network.play.client.C03PacketPlayer$C05PacketPlayerLook.func_148833_a(SourceFile:98)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@681b7a0a
Stacktrace:
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1272138896 bytes (1213 MB) / 2699030528 bytes (2573 MB) up to 25716129792 bytes (24524 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx24G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 13, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 31 mods loaded, 31 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.5.120} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
    UCHIJAAAA   BinniePatcher{1.4.1} [Binnie Patcher](minecraft.jar) 
    UCHIJAAAA   bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) 
    UCHIJAAAA   Treecapitator{1.7.10} [Treecapitator]([1.7.10]Treecapitator-universal-2.0.4.jar) 
    UCHIJAAAA   Forestry{4.2.8.56} [Forestry for Minecraft](forestry_1.7.10-4.2.8.56.jar) 
    UCHIJAAAA   BinnieCore{2.0-pre14} [Binnie Core](binnie-mods-2.0-pre14.jar) 
    UCHIJAAAA   Botany{2.0-pre14} [Botany](binnie-mods-2.0-pre14.jar) 
    UCHIJAAAA   ExtraBees{2.0-pre14} [Extra Bees](binnie-mods-2.0-pre14.jar) 
    UCHIJAAAA   ExtraTrees{2.0-pre14} [Extra Trees](binnie-mods-2.0-pre14.jar) 
    UCHIJAAAA   Genetics{2.0-pre14} [Genetics](binnie-mods-2.0-pre14.jar) 
    UCHIJAAAA   endercore{1.7.10-0.2.0.31_beta} [EnderCore](EnderCore-1.7.10-0.2.0.31_beta.jar) 
    UCHIJAAAA   inventorytweaks{1.58-147-645ca10} [Inventory Tweaks](InventoryTweaks-1.58-147.jar) 
    UCHIJAAAA   journeymap{@JMVERSION@} [JourneyMap](journeymap-1.7.10-5.1.0-unlimited.jar) 
    UCHIJAAAA   redgear_core{2.1.3} [Red Gear Core](RedGearCore-1.7.10-2.1.3.jar) 
    UCHIJAAAA   redgear_morebackpacks{2.2.2} [More Backpacks](More Backpacks-1.7.10-2.2.2.jar) 
    UCHIJAAAA   NEIAddons{1.12.14.40} [NEI Addons](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   neiintegration{1.1.1} [NEI Integration](NEIIntegration-MC1.7.10-1.1.1.jar) 
    UCHIJAAAA   neresources{0.1.0.ManuallyBuilt} [Not Enough Resources](NotEnoughResources-1.7.10-0.1.0-122.jar) 
    UCHIJAAAA   Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHIJAAAA   wailaplugins{MC1.7.10-0.2.0-23} [WAILA Plugins](WAILAPlugins-MC1.7.10-0.2.0-23.jar) 
    UCHIJAAAA   witchery{0.24.1} [Witchery](witchery-1.7.10-0.24.1.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['xNxExOx'/138895, l='New World', x=90,30, y=65,00, z=225,01]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Vexatos** [comment]
> redgear.morebackpacks.backpacks.BackpackLogistic

This crash is related to [More Backpacks](http://minecraft.curseforge.com/projects/chemcraft-more-backpacks), not Forecaster's Backpacks.

**Comment by Kubikx** [comment]
ups sorry my mistake
